CREATE TABLESPACE DBO LOGGING DATAFILE '/u01/app/oracle/oradata/XE/DBO.dbf' SIZE 100m AUTOEXTEND ON NEXT 100m EXTENT MANAGEMENT LOCAL;
CREATE USER SITEAIR_RELEASE IDENTIFIED BY SITEAIR_RELEASE DEFAULT TABLESPACE DBO QUOTA UNLIMITED ON DBO;
GRANT CREATE SESSION TO SITEAIR_RELEASE;
ALTER USER SITEAIR_RELEASE IDENTIFIED BY SITEAIR_RELEASE ACCOUNT UNLOCK;
ALTER USER SITEAIR_RELEASE DEFAULT ROLE ALL;
CREATE OR REPLACE DIRECTORY DUMP_DIR AS '/dmp';
GRANT READ, WRITE ON DIRECTORY DUMP_DIR TO SITEAIR_RELEASE;
